application:
  language: 'en'
  temp: '/tmp'
  overrides:
    config:
      skip-validate-site-uuid: true
  cache:
    rebuild:
      arguments:
        cache: all
  config:
    export:
      options:
        remove-uuid: true
        remove-config-hash: true
